data:
    seqs: ['2012-01-08', '2012-08-20', '2013-04-05']
    camera: 4
    undistort: true
model:
    name: 'pooling_net'
    #normalize: true
weights: 'resnet_v1_50/resnet_v1_50.ckpt'
#weights: 'delf_v1_20171026/model/variables/variables'
