data:
    name: 'nclt'
    test_seq: ['2012-01-08', '2012-08-20', '2013-02-23']
    camera: 4
    #preprocessing:
        #resize: false
        #grayscale: false
model:
    name: 'delf'
    use_attention: true
    normalize_input: true
    normalize_feature_map: true
    image_channels: 1
weights: 'delf_v1_20171026/model/variables/variables'
