data:
    name: 'nclt'
    triplet_file: 'triplets_5seqs.npy'
    #test_seq: ['2012-01-08', '2012-08-20', '2013-02-23']
    validation_size: 100
    camera: 4
    cache_in_memory: true
model:
    name: 'delf_triplets'
    batch_size: 5
    eval_batch_size: 10
    learning_rate: 0.001
    normalize_feature_map: true
    train_attention: true
    triplet_margin: 0.2
    dimensionality_reduction: 40
    image_channels: 1
weights: 'delf_v1_20171026/model/variables/variables'
train_iter: 2000000
validation_interval: 200
