data:
    name: 'nclt'
    test_seq: ['2012-01-08', '2012-08-20', '2013-02-23']
    validation_size: 200
    camera: 4
    cache_in_memory: true
model:
    name: 'mobilenetvlad'
    dropout_keep_prob: null
    intermediate_proj: 0
    dimensionality_reduction: 4096
    depth_multiplier: 1.4
    #resize_input: 2.0
    n_clusters: 64
    train_backbone: true
    train_vlad: true
    batch_size: 16
    eval_batch_size: 16
    learning_rate: 0.001
    image_channels: 1
train_iter: 150000
validation_interval: 500
