data:
    name: 'descriptor_distillation'
    cache_in_memory: true
    truncate: 90000
    image_folders: ['datasets/google_landmarks/images']
    descriptor_folders: ['datasets/google_landmarks/descriptors']
    validation_size: 192
model:
    name: 'mobilenetvlad'
    dropout_keep_prob: null
    intermediate_proj: 0
    dimensionality_reduction: 4096
    depth_multiplier: 0.35
    #resize_input: 2.0
    n_clusters: 32
    train_backbone: true
    train_vlad: true
    batch_size: 16
    eval_batch_size: 16
    learning_rate: 0.001
    image_channels: 1
weights: 'mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt'
train_iter: 150000
validation_interval: 500
