data:
    name: 'nclt'
    test_seq: ['2012-01-08', '2012-08-20', '2013-02-23', '2012-01-22', '2012-03-31', '2012-11-04', '2014-04-05', '2012-05-11']
    camera: 4
    #preprocessing:
        #resize: false
        #grayscale: false
model:
    name: 'delf'
    use_attention: false
    normalize_input: true
    image_channels: 1
#weights: 'resnet_v1_50/resnet_v1_50.ckpt'
weights: 'delf_v1_20171026/model/variables/variables'
