data:
    name: 'nclt'
    #training_triplets: 'triplets_5seqs.npy'
    #validation_triplets: 'triplets_val_4seqs.npy'
    test_seq: ['2012-01-08', '2012-08-20', '2013-02-23', '2012-01-22', '2012-03-31', '2012-11-04', '2013-04-05', '2012-05-11']
    validation_size: 200
    camera: 4
    cache_in_memory: true
model:
    name: 'netvlad_triplets'
    batch_size: 5
    eval_batch_size: 10
    intermediate_proj: 100
    n_clusters: 32
    learning_rate: 0.001
    triplet_margin: 0.2
    dimensionality_reduction: 40
    proj_regularizer: 0
    image_channels: 1
#weights: 'delf_v1_20171026/model/variables/variables'
#weights: 'model.ckpt-1001'
train_iter: 100000
validation_interval: 200
#save_interval: 1000
#keep_checkpoints: 10
